apiVersion: v1
kind: Pod
metadata:
  name: cm-test
  labels:
    app: vol
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /velocity
      name: test
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
  volumes:
  - name: test
    configMap:
      name: foobar
